scheme: Gemini
language: zh-CN
cache:
  enable: true
minify: true
darkmode: true
menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat
site_state: true

# 社交账号的小图标和链接
social:
  GitHub: https://github.com/charlestang || fab fa-github
  #E-Mail: mailto:yourname@gmail.com || fa fa-envelope
  #Weibo: https://weibo.com/yourname || fab fa-weibo
  Twitter: https://twitter.com/charlestang || fab fa-twitter
  #FB Page: https://www.facebook.com/yourname || fab fa-facebook
  #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
  #YouTube: https://youtube.com/yourname || fab fa-youtube
  #Instagram: https://instagram.com/yourname || fab fa-instagram
  #Skype: skype:yourname?call|chat || fab fa-skype

# 在网站右上角，展示一个 GitHub 的 Ribbon
github_banner:
  enable: true
  permalink: https://github.com/charlestang

# 文章元信息，要求不展示文章更新时间
post_meta:
  updated_at:
    enable: false

# 默认情况下，tag 在文章末尾，用 # 开头，可以用此选项，替换成图标
tag_icon: true


# 相关文章插件 npm install hexo-related-posts && hexo clean
#related_posts:
#  enable: true
#  icon: fa fa-signs-post

footer:
  since: 2008

open_graph:
  enable: true
  options: blog

post_edit:
  enable: true

codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  # See: https://github.com/chriskempson/tomorrow-theme
  theme:
    light: base16/solarized-light
    dark: tomorrow-night-bright
  # Add copy button on codeblock
  copy_button:
    enable: false
    # Show text copy result.
    show_result: false
    # Available values: default | flat | mac
    style:

local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: manual
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false

google_analytics:
  tracking_id: G-LJKX5X3SP3
  only_pageview: false

busuanzi_count:
  enable: true
  post_views: true
  post_views_icon: far fa-eye
  total_views: true
  total_views_icon: fa fa-eye

reading_progress:
  enable: true
  # Available values: left | right
  start_at: left
  # Available values: top | bottom
  position: top
  reversed: false
  color: "#37c6c0"
  height: 2px

back2top:
  enable: true
  sidebar: true
  scrollpercent: true
